build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Bonjour,$GITLAB_USER_LOGIN"

# Add a job to push commits to GitHub
sync-to-github:
  stage: deploy
  script:
    - git remote add github https://richtofen60%40gmail.com:${GITHUB_TOKEN}@github.com/SkyBlyvion/PapaPizza.git
    - git push --mirror github
  only:
    - main

