build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Bonjour,$GITLAB_USER_LOGIN"

# Add a job to push commits to  GitHub
sync-to-github:
  stage: deploy
  script:
    # Add or update the GitHub remote
    - if git remote | grep -q github; then git remote set-url github https://richtofen60%40gmail.com:${GITHUB_TOKEN}@github.com/SkyBlyvion/PapaPizza.git; else git remote add github https://richtofen60%40gmail.com:${GITHUB_TOKEN}@github.com/SkyBlyvion/PapaPizza.git; fi
    # Push only the current branch to GitHub
    - git push github main
  only:
    - main # Run this job only for the main branch



